blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using urlfounder
    url: https://github.com/chainreactors/urlfounder/discussions/categories/q-a
    about: Ask a question or request support for using urlfounder

  - name: Share idea / feature to discuss for urlfounder
    url: https://github.com/chainreactors/urlfounder/discussions/categories/ideas
    about: Share idea / feature to discuss for urlfounder

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication