blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using subfinder
    url: https://github.com/projectdiscovery/subfinder/discussions/categories/q-a
    about: Ask a question or request support for using subfinder

  - name: Share idea / feature to discuss for subfinder
    url: https://github.com/projectdiscovery/subfinder/discussions/categories/ideas
    about: Share idea / feature to discuss for subfinder

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication